name: clipboard_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # router
  go_router: ^17.0.1

  # toast
  delightful_toast: ^1.1.0

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # bloc
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # svg
  flutter_svg: ^2.2.3

  # logger
  logger: ^2.6.2

  # get_it
  get_it: ^9.2.0

  # reorderables
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/icons/svg/
